language: python
matrix:
  include:
  - python: 3.6
install:
- pip install coveralls
- pip install -r requirements.txt
script:
- coverage run --omit '/home/travis/virtualenv*' -m unittest -v
after_success: coveralls
deploy:
  provider: codedeploy
  revision_type: github
  access_key_id: AKIAJINEKHLOF7ODMQEQ
  secret_access_key:
    secure: rPxQX5sh0+zc5hiO26Jyc4ttxiefZaCZcpYq/lEUuDU0CbovkTu2WaT7sdIwSaeKjO4nGA0LK/4oW+DfcECNpZd4xNhunTSoto2Bp/EtFAKx6UJEkXMLGJQ91YJ1pMHXmNjyH/farcQpIE2W7uiKmv25A3eUet8/bBijx/jQW0iXWgqbOgIwmBF6RGHXoPmyFJL3RxmA7kx5BgwXCXH1eupi7NA+sQVt9hqjd+UhWxS3TcvBO86Q/qcREfKJz/nix5dzvo91i0PONAxSVkVQgeJuZmRQcNPlZcq5YFsHAOKBOKCShfLNrrS3PX8qFTHoj9wewrXdExD8gzy6PUmQVxI1XXDU6Zwoi8tOzHtc/v+tXIX+pNVDPt1xKiqw/9px271hHCSmB4/9jqTMmplghZFUxg1TP0Hawn604dK8hjsqKFb8YTBxfzxlhWcFJ0JcehPWuD+vBwroD/UTIHIAuQ3mBoDDvUQKe+2N3i5xSaGLAQImtG3U6HlYHNxySNfOaiaFiRytQlmpFT8/eBbfykA5vFm+kOMjHJygNfx3lmXmXY/xMet9rpfV6YpDgpoIvgt/W2yGd4xQDBwNj0j7tk2LRYJjHfBjCpO+8aMpktY+mzGMeYTX1I1wwbR8kqOtX++7fyxHeBtwAT9bMLi3NogagLKXNnI22iweQZDbh74=
  application: your-print-is-ready
  deployment_group: your-print-is-ready
  on:
    branch: master
