language: python
matrix:
  include:
  - python: 3.6
install:
- pip install coveralls
- pip install -r requirements.txt
script:
- coverage run --omit '/home/travis/virtualenv*' -m unittest -v
after_success: coveralls
deploy:
  provider: codedeploy
  revision_type: github
  access_key_id: AKIAI2DYGCKZPAUD5PBQ
  secret_access_key:
    secure: gx7nYiz0UbxdO5e4f52BjuXGfyCpxQVElfk75lvOAojPNLkcBuQUsAzFGfPEKWC8CehpY/fS9VDk/8ubxopXDB8u8A/Gu/No9HhrQ9mNt6G47PSu/lszR/k+t2WFGvbHHctp8eSKeSYbGN2anq/HQMkx7QH9d4g9OEuoAhMxAcfKu+DrRMp4YJRkZDuCI0O5kG32ODLtrQlMalPDR397FHpX/lK1wd6MJCLsPkx6YRp7nuEKrCOpZy0qgmswKNLNO+RomcxzwKX7FZtYARbizeXgRA2KoFh26G6naucDg0SiOtTD8KzIZzMO4lki8kspxhHZBtrmG7Vw3vjz3A8TbagCD/UGKvxysHrVvbt4RgyOfkqHPMo0N3su/O+S9JJcZEZJhgExorFSaN91HLpqMHN0okLKO8/WouWcsaA0EOmZq6jrJBRMstwFvXWwJpvTwnP9KayDop54UdjcHtH/Sz1ddBH0v986rg0UWLLYqJG6bCAoE/asc6vK+5QckVG1FouNiymGvtokgLK/VAFBF7aXcifeiBMdxgXWSKwBPkWf5FrDutbuOq7YrSBsqtAWAJ1FIYCE39bxlIpNPBxYzAvbMFyUSvBH1GZIpUj1NOKldXgFO8J5FAuhE22Z8/KxhifnvbaSBhq7gAUVqwKZ2M4hSr6ihIdJluVJy37q/4s=
  application: your-print-is-ready
  deployment_group: your-print-is-ready
  on:
    branch: master
